# Execution environments

Troubleshoot issues with execution environments.

# Issue - Cannot select the "Use in Controller" option for execution environment image on private automation hub

You cannot use the Use in Controller option for an execution environment image on private automation hub. You also receive the error message: “No Controllers available”.

To resolve this issue, connect automation controller to your private automation hub instance.

1. Change the /etc/pulp/settings.py file on private automation hub and add one of the following parameters depending on your configuration:
* Single controller

```
CONNECTED_ANSIBLE_CONTROLLERS = ['<https://my.controller.node>']
```

* Many controllers behind a load balancer

```
CONNECTED_ANSIBLE_CONTROLLERS = ['<https://my.controller.loadbalancer>']
```

* Many controllers without a load balancer

```
CONNECTED_ANSIBLE_CONTROLLERS = ['<https://my.controller.node1>', '<https://my.controller2.node2>']
```

2. Stop all of the private automation hub services:

```
# systemctl stop pulpcore.service pulpcore-api.service pulpcore-content.service pulpcore-worker@1.service pulpcore-worker@2.service nginx.service redis.service
```

3. Restart all of the private automation hub services:

```
# systemctl start pulpcore.service pulpcore-api.service pulpcore-content.service pulpcore-worker@1.service pulpcore-worker@2.service nginx.service redis.service
```


* Verify that you can now use the Use in Controller option in private automation hub.